####
#### Transporter Group
####

transporterConfigForm:
  kind: panel.form
  label: "Site-wide Transporter Settings"
  name: transporterConfigForm
  id: transporter-config-form
  contentType: json
  method: POST
  element:
    style:
      padding: 20px 0
  action: "/xapi/transporter/path-mapping"
  contents:
    serverRootPath:
      kind: panel.input.text
      name: serverRootPath
      label: Server Path Prefix
      element:
        title: XNAT Path Prefix
      description: >
        Enter the server path to the XNAT_HOME mount, i.e. "/docker/my-data/XNAT"
    xnatRootPath:
      kind: panel.input.text
      name: xnatRootPath
      label: XNAT Path Prefix
      element:
        title: XNAT Path Prefix
      description: >
        Enter the local XNAT_HOME path, i.e. "/data/xnat"

transporterRemoteStatusPanel:
  kind: panel.dataTable
  name: transporterRemoteStatusTable
  label: Remote App Status
  load: /xapi/transporter/heartbeat
  items:
    id: ~!
    remoteAppId: Remote App Id
    remoteHost: Remote Host
    status: Status
    message: Message
    formattedUptime: Uptime
    formattedTimestamp: Last Update

transporterActivityPanel:
  kind: panel
  name : transporterActivity
  label: Site-wide Transporter Activity
  contents:
    transporterActivityDescription:
      tag: div.message
      contents:
        "The Transporter Activity panel displays all Transporter activity across the site."
    transporterActivityTable:
      tag: "div#transporter-activity-table"
    transporterActivityScript:
      tag: script|src="~/scripts/xnat/plugin/transporter/transporter-activity-admin.js"
    renderTransporterActivityTable:
      tag: script
      content: >
        XNAT.plugin.transporter.activity.init('transporter-activity-table');    

snapshotPanel:
  kind: panel
  name : snapshots
  label: Site-wide Snapshots
  contents:
    snapshotDescription:
      tag: div.message
      contents:
        "All snapshots across the site."
    snapshotTable:
      tag: "div#transporter-snapshot-table"
    snapshotScript:
      tag: script|src="~/scripts/xnat/plugin/transporter/transporter-snapshot-admin.js"
    renderSnapshotTable:
      tag: script
      content: >
        XNAT.plugin.transporter.snapshots.init('transporter-snapshot-table');



#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
  kind: tabs
  name: transporterAdminPage
  label: Administer Transporter
  meta:
    tabGroups:
      transporterTabGroup: Transporter
  contains: tabs
  tabs:
    snapshotTab:
      kind: tab
      name: snapshotTab
      label: Snapshots
      group: transporterTabGroup
      active: true
      contents:
        ${snapshotPanel}
    transporterRemoteStatusTab:
      kind: tab
      name: transporterRemoteStatusTab
      label: Remote App Status
      group: transporterTabGroup
      active: false
      contents:
        ${transporterRemoteStatusPanel}
    transporterActivityTab:
      kind: tab
      name: transporterActivityTab
      label: Transporter Activity
      group: transporterTabGroup
      active: false
      contents:
        ${transporterActivityPanel}
    transporterConfigTab:
      kind: tab
      name: transporterConfigTab
      label: Configuration
      group: transporterTabGroup
      active: false
      contents:
        ${transporterConfigForm}
